### ISSUE TITLE
[Error] reqwest::Error "missing field `response`"

### ISSUE THREAD

**Issue by Kare-Udon** [WOo0W/pixivcrab-rs#1]
Hi! When I am trying to run your example code, something went wrong.

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HTTP { source: reqwest::Error { kind: Decode, source: Error("missing field `response`", line: 1, column: 110) } }'```

My reqwest version is `0.11.12`.

I am pretty sure my Pixiv Refresh Token is correct and I can not locate the error.

Could you please help me? If you need more information, please let me know.

**Comment by ComfyFluffy** [comment]
Sorry for not replying in time. I haven't checked my email for a long time.

The error seems to be about JSON parsing, which means the server returned a JSON with an error message that can not be parsed. This could be an issue of an incorrect Refresh Token.

I am refactoring the code to return a better error hint. See you in v0.5.

**Comment by ComfyFluffy** [comment]
0.5.0 has been released. Authing should return error messages if the status code is not ok.

**Comment by Kare-Udon** [comment]
> 0.5.0 has been released. Authing should return error messages if the status code is not ok.

Thank you! I will try it asap.
